version: "3.9"

services:
  server:
    image: node:20-alpine
    container_name: mycontacts-server-dev
    working_dir: /app
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    command: sh -c "npm install && npm run start"
    environment:
      - API_PORT=${API_PORT:-5555}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-mycontacts}
      - JWT_SECRET=${JWT_SECRET_KEY}
    ports:
      - "${API_PORT:-5555}:5555"
    restart: unless-stopped

  client:
    image: node:20-alpine
    container_name: mycontacts-client-dev
    working_dir: /app
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: sh -c "[ -d node_modules ] || npm ci && npm start"
    environment:
      - PORT=3000
      - HOST=0.0.0.0

      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300

      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=${CLIENT_PORT:-3000}

      - BROWSER=none

      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://server:${API_PORT:-5555}}
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  server_node_modules:
  client_node_modules:

networks:
  default:
    name: mycontacts-net-dev
